### ISSUE TITLE
Question: v8 release?

### ISSUE THREAD

**Issue by casret** [Callidon/bloom-filters#10]
I would like to use a cuckoo filter, and saw some work on improving it (ergonomics, and looks like speed?) in the master branch that hasn't been released.  When do you think it will be in shape to go out?

**Comment by folkvir** [comment]
We are working on the API and are a lot busy in work. For the moment you can try the master and fix the last commit as release.  If you plan to use only Cuckoo Filter, you can begin to write some stuff on your side. The API wont change in the future ;) But the rest will. So be careful.
The "v8" will be released soon certainly as the 1.0.0 as we have breaking API changes. I will close this issue when the new version will be released.

**Comment by folkvir** [comment]
The master is now stable, future modifications will be documentation and comments. 
A release should be done during the next week.

**Comment by folkvir** [comment]
@casret The cuckoo filter has now a third argument for add method. 
```js
add(element, THROW_ERROR, DESTRUCTIVE)
```
- THROW_ERROR when set to true throw an error instead of returning false
- DESTRUCTIVE when set to true  do not rollback on kicks if the filter is considered as full, aka the add( ) method throw an error or return false. By default,  it is set to false and the structure rollback to its initial state, before calling the method.

**Comment by folkvir** [comment]
@Callidon Documentation pushed, can you bump the version?

**Comment by Callidon** [comment]
The version has been bumped to 0.8 and published on NPM. Enjoy :octocat:
