### ISSUE TITLE
[Bug?] npm install produces only a api.js file

### ISSUE THREAD

**Issue by baslr** [Callidon/bloom-filters#38]
`npm install` installs version `1.3.7`.  
The npm package only contains a `api.js` in the `dist` directory. Did I missed something?  
The package can not run because all files that are required in the  `api.js` file are not there.

**Comment by Callidon** [comment]
Hi, indeed there is a serious bug with the `1.3.7`, I've managed to reproduce it locally. I will look into this right now and release a new mini version when it's corrected.

Sorry for the inconvenience, and thank you for reporting this bug!

**Comment by Callidon** [comment]
Well, that's an embarrassing one 🤣
The project was missing a `.npmignore` file, which is required when using `yarn`. Otherwise, it will default to the `.gitignore` file during release and ignore the distribution files located in the dist folder. I've added a `.npmignore` file that should do the trick. 

@baslr I've released a new version 1.3.8, can you please test if everything is working as intended now?

**Comment by folkvir** [comment]
@Callidon I confirm a `npm install bloom-filters` is sane and in 1.3.8
