### ISSUE TITLE
Unexpected behaviour in CuckooFilter

### ISSUE THREAD

**Issue by mixdev** [Callidon/bloom-filters#9]
See the example. Many false positives (It happens especially after the first result in a row.) What am I doing wrong?

    const { CuckooFilter } = require('bloom-filters')
    let filter = new CuckooFilter(15, 3, 2)

     filter.add('alice')
     filter.add('andrew')
     filter.add('bob')
     filter.add('sam')

     filter.add('alice')
     filter.add('andrew')
     filter.add('bob')
     filter.add('sam')

    // lookup for some data
    console.log(filter.has('samx')) // output: false [ok]
    console.log(filter.has('samy')) // output: true [?]
    console.log(filter.has('alice')) // output: true [ok]
    console.log(filter.has('joe')) // output: true [?]
    console.log(filter.has('joe')) // output: true [?]

Version 0.7.1

**Comment by folkvir** [comment]
We are investigating this. Thank you for sharing this unexpected behavior 👍

**Comment by folkvir** [comment]
Thank you very much for sharing this issue. 

The bug seems to come from our hashing library, you did nothing wrong. 
Elements are hashed using either the 32 or the 64 bits. For some reason, a bug I guess, the 32bits version  returns only the hash created but not a 32 length version. It wont be a maximum of 32 elements for sure but can be less. For this reason I added leading zeroes to create a 32 length string. This mechanism works well when you dont touch the hash. 

The Cuckoo Filter with its fingerprint attribute takes the first k-characters. It means similar hashes less than 32 characters; eg: 10 characters, with a fingerprint of 3 like in the example, the fingerprint will always be '000' which leads to A LOT OF false positive.

I corrected this by forcing the cuckoo filter to use the 64 bits version. 
It seems to work properly now. Can you confirm this by testing the master branch? 

A.Grall

**Comment by folkvir** [comment]
Yes it should correctly work now. 
Please verify by testing the master branch.
I also added two methods: 
```js
// first method
const numberOfDesiredItemsToInsert = 100
const error_rate = 0.01
const bucketSize = 2
const filter = CuckooFilter.create(numberOfDesiredItemsToInsert, error_rate, bucketSize)
for (let i = 0; i<numberOfDesiredItemsToInsert; i++) filter.add('' + i)
for (let i = 0; i<numberOfDesiredItemsToInsert; i++) console.log(filter.has('' + i))
// should log 100x true
// second method
console.log(filter.fpr)
// it returns the actual error rate of this CuckooFilter based on the actual load of the filter. 
// It should be less than the desired error_rate you previously defined using the create method.
```

But you can still create the filter using the standard way if you want to customize all parameters.

**Comment by mixdev** [comment]
Awesome. That was quick. Does it mean that it all other filters too work ok? I guess BloomFilter also had false positives. Sorry I don/t have the code now.

**Comment by mixdev** [comment]
Just tried the master branch. Can conform that  the earlier code works fine. 
    const { CuckooFilter } = require('bloom-filters')
    let filter = new CuckooFilter(15, 3, 2)

    for(i=20000; i<30003; i++) filter.add(i.toString());

    for(i=30000; i<30005; i++) {
	console.log(i,filter.has(i.toString()),filter.has(i.toString()),filter.has(i.toString())) 
    }

<img width="251" alt="Screen Shot 2019-10-01 at 12 02 29 AM" src="https://user-images.githubusercontent.com/38874/65905920-2507ef80-e3df-11e9-9b5d-9b678faf8de5.png">
So there are some false positives. It's kind of one among 3 runs. Is this expected? Should I tweak the filter for this code?

**Comment by folkvir** [comment]
This is the expected behavior yes. You inserted a lot of elements in a small filter and you get an error rate close to 1.
I suggest you to read the paper if you want to know how to tune these parameters. But in short:
```js
CuckooFilter.create(10000, 0.01, 4)
```
It creates a CuckooFilter with an error rate of 0.01, a bucket size of 4 and  for 10 000 inserted elements.  Every Bloom Filter needs to be tune in order to accept a specified number of elements with an acceptable error rate. Formulae are always specified in all papers and are relatively close one from another. Thus, if you insert more elements than allowed then the error rate will increase and querying the set will lead to a lot of false positive. 
I agree there is a confusion for this Filter as the constructor do not match previous constructors of other filters. That's why I added the `.create` function.

**Comment by folkvir** [comment]
It should be completely fixed. Thus I added new tests (for several filters) to ensure that the false positive rate stay correct for 1000 insertion and queries. 

I will close this issue as everything is fixed now. 
And will tag and push the master to **v0.8** soon (in the end of the week).
Meantime, if you have any problem relative to the master branch feel free to open an issue.

**Comment by sansato** [comment]
can you publish v0.8 with the updates?

**Comment by folkvir** [comment]
> can you publish v0.8 with the updates?

see #10
